
module.exports = [
    {
        title: 'To Kill a Mockingbird',
        author: 'Harper Lee',
        price: 15.99,
        rating: 4.5,
        tags: ["Classic", "Drama", "Race Relations"],
    },
    {
        title: '1984',
        author: 'George Orwell',
        price: 12.99,
        rating: 4.8,
        tags: ['Dystopian', 'Political'],
    },
    {
        title: 'The Great Gatsby',
        author: 'F. Scott Fitzgerald',
        price: 14.99,
        rating: 4.2,
        tags: ['Classic', 'Romance', 'Roaring Twenties'],
    },
    {
        title: 'One Hundred Years of Solitude',
        author: 'Gabriel García Márquez',
        price: 18.99,
        rating: 4.6,
        tags: ['Magical Realism', 'Family Saga'],
    },
    {
        title: 'Brave New World',
        author: 'Aldous Huxley',
        price: 16.99,
        rating: 4.3,
        tags: ['Dystopian', 'Science Fiction'],
    },
    {
        title: 'The Catcher in the Rye',
        author: 'J.D. Salinger',
        price: 13.99,
        rating: 4.1,
        tags: ['Coming of Age', 'Teen'],
    },
    {
        title: 'The Hobbit',
        author: 'J.R.R. Tolkien',
        price: 17.99,
        rating: 4.7,
        tags: ['Fantasy', 'Adventure'],
    },
    {
        title: 'The Lord of the Rings',
        author: 'J.R.R. Tolkien',
        price: 21.99,
        rating: 4.9,
        tags: ['Fantasy', 'Epic'],
    },
    {
        title: 'Pride and Prejudice',
        author: 'Jane Austen',
        price: 11.99,
        rating: 4.4,
        tags: ['Classic', 'Romance'],
    },
    {
        title: 'Crime and Punishment',
        author: 'Fyodor Dostoevsky',
        price: 19.99,
        rating: 4.7,
        tags: ['Psychological Thriller', 'Russian Literature'],
    },
    {
        title: 'The Alchemist',
        author: 'Paulo Coelho',
        price: 14.99,
        rating: 4.6,
        tags: ['Philosophical', 'Adventure'],
    },
    {
        title: 'Moby-Dick',
        author: 'Herman Melville',
        price: 20.99,
        rating: 4.0,
        tags: ['Adventure', 'Whaling'],
    },
    {
        title: 'Frankenstein',
        author: 'Mary Shelley',
        price: 16.99,
        rating: 4.2,
        tags: ['Gothic', 'Science Fiction'],
    },
    {
        title: 'The Picture of Dorian Gray',
        author: 'Oscar Wilde',
        price: 15.99,
        rating: 4.5,
        tags: ['Classic', 'Gothic', 'Philosophical'],
    },
    {
        title: 'Wuthering Heights',
        author: 'Emily Brontë',
        price: 18.99,
        rating: 4.3,
        tags: ['Gothic', 'Romance'],
    },
    {
        title: 'Sapiens: A Brief History of Humankind',
        author: 'Yuval Noah Harari',
        price: 22.99,
        rating: 4.8,
        tags: ['History', 'Anthropology'],
    },
    {
        title: 'The Da Vinci Code',
        author: 'Dan Brown',
        price: 13.99,
        rating: 4.1,
        tags: ['Mystery', 'Thriller'],
    },
    {
        title: 'The Girl with the Dragon Tattoo',
        author: 'Stieg Larsson',
        price: 16.99,
        rating: 4.4,
        tags: ['Mystery', 'Crime'],
    },
    {
        title: 'The Road',
        author: 'Cormac McCarthy',
        price: 19.99,
        rating: 4.6,
        tags: ['Post-Apocalyptic', 'Dystopian'],
    },
    {
        title: 'The Hitchhiker\'s Guide to the Galaxy',
        author: 'Douglas Adams',
        price: 15.99,
        rating: 4.7,
        tags: ['Science Fiction', 'Comedy'],
    },
    {
        title: 'The Brothers Karamazov',
        author: 'Fyodor Dostoevsky',
        price: 18.99,
        rating: 4.8,
        tags: ['Philosophical', 'Russian Literature'],
    },
    {
        title: 'The Chronicles of Narnia',
        author: 'C.S. Lewis',
        price: 16.99,
        rating: 4.5,
        tags: ['Fantasy', 'Adventure'],
    },
    {
        title: 'The Shining',
        author: 'Stephen King',
        price: 14.99,
        rating: 4.2,
        tags: ['Horror', 'Psychological Thriller'],
    },
    {
        title: 'The Handmaid\'s Tale',
        author: 'Margaret Atwood',
        price: 20.99,
        rating: 4.6,
        tags: ['Dystopian', 'Feminist Literature'],
    },
    {
        title: 'The Old Man and the Sea',
        author: 'Ernest Hemingway',
        price: 12.99,
        rating: 4.0,
        tags: ['Adventure', 'Classic'],
    },
    {
        title: 'The Martian',
        author: 'Andy Weir',
        price: 17.99,
        rating: 4.7,
        tags: ['Science Fiction', 'Survival'],
    },
    {
        title: 'The Grapes of Wrath',
        author: 'John Steinbeck',
        price: 19.99,
        rating: 4.3,
        tags: ['Classic', 'Social Commentary'],
    },
    {
        title: 'The Silence of the Lambs',
        author: 'Thomas Harris',
        price: 15.99,
        rating: 4.4,
        tags: ['Thriller', 'Crime'],
    },
    {
        title: 'The Hound of the Baskervilles',
        author: 'Arthur Conan Doyle',
        price: 13.99,
        rating: 4.5,
        tags: ['Mystery', 'Detective'],
    },
    {
        title: 'The Count of Monte Cristo',
        author: 'Alexandre Dumas',
        price: 22.99,
        rating: 4.9,
        tags: ['Adventure', 'Revenge'],
    },
];

